# Generated by Django 4.2.23 on 2026-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='authorization_time',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='authorization_time',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
