# Generated by Django 4.2.23 on 2025-12-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesitem_sale_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
    ]
