# Generated by Django 4.2.23 on 2025-10-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'ordering': ['name'], 'verbose_name': 'Factory', 'verbose_name_plural': 'Factories'},
        ),
        migrations.RemoveField(
            model_name='factory',
            name='admin_region',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='unique_location',
        ),
        migrations.AlterField(
            model_name='factory',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum production capacity (e.g., units per day).', null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
