# Generated by Django 4.2.23 on 2025-10-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_factory_options_remove_factory_admin_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(default='CTY-20251012-36E', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.city'),
            preserve_default=False,
        ),
    ]
