# Generated by Django 4.2.23 on 2025-10-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregion',
            name='code',
        ),
        migrations.RemoveField(
            model_name='adminregion',
            name='description',
        ),
    ]
