# Generated by Django 4.2.23 on 2025-10-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
    ]
