# Generated by Django 4.2.23 on 2025-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_warehouse_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
