# Generated by Django 4.2.23 on 2025-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_warehouse_capacity_alter_warehouse_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
