# Generated by Django 4.2.23 on 2025-09-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_alter_warehouse_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('warehouse', 'product')},
        ),
    ]
