# Generated by Django 4.2.23 on 2025-09-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementlog',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
