# Generated by Django 4.2.23 on 2025-10-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
