# Generated by Django 4.2.23 on 2025-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poso', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_product_per_PO'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.UniqueConstraint(fields=('sales_order', 'product'), name='unique_product_per_SO'),
        ),
    ]
