# Generated by Django 4.2.23 on 2025-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poso', '0003_salesorder_source_store'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorderitem',
            name='unique_product_per_SO',
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['sales_order', 'product'], name='poso_saleso_sales_o_5b42d6_idx'),
        ),
    ]
