# Generated by Django 4.2.23 on 2025-10-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpackage',
            options={'ordering': ['name'], 'verbose_name': 'Product Package', 'verbose_name_plural': 'Product Packages'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_size',
        ),
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Optional reference to a defined package type', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productpackage'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Optional package dimensions (LxWxH in cm).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='size',
            field=models.CharField(blank=True, help_text='Physical size or capacity, e.g., 500g, 1L, 20kg, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms, if applicable.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces'), ('box', 'Box'), ('pack', 'Pack'), ('na', 'Not Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
