# Generated by Django 4.2.23 on 2025-10-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productpackage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='factory',
            new_name='company',
        ),
    ]
