# Generated by Django 4.2.23 on 2025-10-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales'), ('transfer', 'Transfer'), ('processing', 'Processing')], default=1, help_text='Reason for this inventory movement', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.company'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='Only_one_type_per_warehouse'),
        ),
    ]
