# Generated by Django 4.2.23 on 2025-10-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_factory_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='requested_by',
        ),
    ]
