# Generated by Django 4.2.23 on 2025-10-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stocktransfer_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='locked_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
