# Generated by Django 4.2.23 on 2025-10-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktransfer_locked_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='locked_amount',
        ),
    ]
