# Generated by Django 4.2.23 on 2025-10-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stocktransfer_locked_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={},
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='authorized_date',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='unit_of_measure',
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_stock_transfer_id'),
        ),
        migrations.AlterModelTable(
            name='stocktransfer',
            table=None,
        ),
    ]
