# Generated by Django 4.2.23 on 2025-10-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stocktransfer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='authorization_time',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='is_authorized',
        ),
    ]
