# Generated by Django 4.2.23 on 2025-10-17 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_remove_stocktransfer_authorization_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='authorization_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='authorized_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
