# Generated by Django 4.2.23 on 2025-10-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stocktransfer_locked_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='locked_amount',
        ),
    ]
