# Generated by Django 4.2.23 on 2025-10-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_stocktransfer_locked_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymovementlog',
            old_name='warehouse',
            new_name='source_warehouse',
        ),
        migrations.AddField(
            model_name='inventorymovementlog',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_destination_warehouse', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorymovementlog',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales'), ('transfer', 'Transfer'), ('processing', 'Processing')], max_length=20),
        ),
    ]
