# Generated by Django 4.2.23 on 2025-12-26 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivingNote',
            fields=[
                ('is_authorized', models.BooleanField(default=False)),
                ('authorization_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('received_by', models.CharField(max_length=100)),
                ('delivery_note_number', models.CharField(blank=True, max_length=50)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchase.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authorized', models.BooleanField(default=False)),
                ('authorization_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.IntegerField()),
                ('authorized_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.goodsreceivingnote')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseorderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
