# Generated by Django 4.2.23 on 2025-10-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poso', '0004_remove_salesorderitem_unique_product_per_so_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending')),
                ('payment_status', models.CharField(default='Unpaid')),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('bank_reference', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='Unpaid')),
                ('sale_item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sales.salesitem')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('order_status', models.CharField(default='Pending')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(default='Unpaid')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='poso.customer')),
            ],
        ),
        migrations.AddField(
            model_name='salesitem',
            name='sale_order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
    ]
