# Generated by Django 4.2.23 on 2025-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
