# Generated by Django 4.2.23 on 2025-10-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_alter_salesorder_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
            preserve_default=False,
        ),
    ]
