# Generated by Django 4.2.23 on 2025-10-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poso', '0004_remove_salesorderitem_unique_product_per_so_and_more'),
        ('sales', '0003_remove_salesitem_product_name_salesitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='poso.customer'),
        ),
    ]
