# Generated by Django 4.2.23 on 2025-10-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_salesitem_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='product',
            new_name='product_name',
        ),
    ]
