# Generated by Django 4.2.23 on 2025-10-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_product_salesitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
