# Generated by Django 4.2.23 on 2025-10-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0007_salesitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='source_whouse',
            field=models.ForeignKey(default='WRH-20251017-EAB', on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
            preserve_default=False,
        ),
    ]
