# Generated by Django 4.2.23 on 2025-10-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0008_salesitem_source_whouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='inventory',
            field=models.ForeignKey(default='INV-20251017-86C', on_delete=django.db.models.deletion.PROTECT, to='inventory.stock'),
            preserve_default=False,
        ),
    ]
